### PR TITLE
Update main.cpp

### PR DESCRIPTION
**Pull request by ztlawton**
Added remaining Workshop types without changing anything else.

### CODE REVIEW

**Comment by JamesBremner** [comment]
Well done.  You are an impressively fast learner and coder!

I will take a little while to check it.

**Comment by JamesBremner** [comment]
I do not see where you have added the new types to the enumeration.  Are you sure that this builds?

**Comment by JamesBremner** [comment]
I have cloned your fork and done a test build.  

It fails!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

```
g++  -std=c++17 -g -D_mingw_ \
-c -o .vscode/obj/main.o ./src/main.cpp -I./include -I../windex/include -I../raven-set -I../../code_ext/boost/boost1_78 
./src/main.cpp: In constructor 'cWorkshop::cWorkshop(eWorkShopType)':
./src/main.cpp:71:9: error: 'ss' was not declared in this scope
   71 |         ss << "Agriculture Chambers (Workshop): ";
      |         ^~
./src/main.cpp:80:25: error: 'biotech' is not a member of 'eWorkShopType'
   80 |     case eWorkShopType::biotech:
      |                         ^~~~~~~
./src/main.cpp:90:25: error: 'electronics' is not a member of 'eWorkShopType'
   90 |     case eWorkShopType::electronics:
      |                         ^~~~~~~~~~~
./src/main.cpp:100:25: error: 'energy' is not a member of 'eWorkShopType'
  100 |     case eWorkShopType::energy:
      |                         ^~~~~~
./src/main.cpp:110:25: error: 'heavyindustry' is not a member of 'eWorkShopType'
  110 |     case eWorkShopType::heavyindustry:
```

**Comment by JamesBremner** [comment]
It is extremely bad practice to commit code that breaks the build.  In many places this would get you fired for cause.

**Comment by JamesBremner** [comment]
I have simplified the build, so it should be easier for you to do your own test builds.  Here is the makefile https://github.com/JamesBremner/workshoplocator/blob/main/.vscode/makefile

**Comment by ztlawton** [comment]
Do you have a good resource describing how to do a test build? Do I need to install Git to do that? I installed Visual Studio Code since that's what came up when I searched "vscode", but it looks like I might need some additional extensions for it?

**Comment by JamesBremner** [comment]
Please enable issues on your repo so we can discuss the details of test building.

Please, please, please read my comments on your commits.

Never, never, never commit without a test build.

**Comment by ztlawton** [comment]
I am reading your comments here, but I don't see comments on the other commit. Am I looking in the wrong place?

**Comment by JamesBremner** [comment]
Two ways to find comments on a commit

- follow the link from the email notification
- open the commit and scroll down
